<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: sam
 * Date: Mon, 06 Apr 2020 04:07:15 +0200
 */

$conf['title'] = 'Sam-Test';
$conf['license'] = 'cc-by-sa';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register,profile_delete,check,rss,subscribe,unsubscribe';
$conf['video_settings'] = 'autoplay';
