<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: admin
 * Date: Thu, 07 Nov 2024 19:31:09 +0000
 */

$conf['title'] = 'Development';
$conf['license'] = 'cc-by-sa';
$conf['youarehere'] = 1;
$conf['dformat'] = '%d.%m.%y, %H:%M:%S';
$conf['useheading'] = '1';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['compress'] = 0;
