<?php

$meta['server']           = array('string','_caution' => 'danger');
$meta['user']             = array('string','_caution' => 'danger');
$meta['password']         = array('password','_caution' => 'danger','_code' => 'base64');
$meta['database']         = array('string','_caution' => 'danger');
$meta['charset']          = array('string','_caution' => 'danger');
$meta['debug']            = array('multichoice','_choices' => array(0,1,2),'_caution' => 'security');
$meta['forwardClearPass'] = array('onoff','_caution' => 'danger');
$meta['TablesToLock']     = array('array','_caution' => 'danger');
$meta['checkPass']        = array('','_caution' => 'danger');
$meta['getUserInfo']      = array('','_caution' => 'danger');
$meta['getGroups']        = array('','_caution' => 'danger');
$meta['getUsers']         = array('','_caution' => 'danger');
$meta['FilterLogin']      = array('string','_caution' => 'danger');
$meta['FilterName']       = array('string','_caution' => 'danger');
$meta['FilterEmail']      = array('string','_caution' => 'danger');
$meta['FilterGroup']      = array('string','_caution' => 'danger');
$meta['SortOrder']        = array('string','_caution' => 'danger');
$meta['addUser']          = array('','_caution' => 'danger');
$meta['addGroup']         = array('','_caution' => 'danger');
$meta['addUserGroup']     = array('','_caution' => 'danger');
$meta['delGroup']         = array('','_caution' => 'danger');
$meta['getUserID']        = array('','_caution' => 'danger');
$meta['delUser']          = array('','_caution' => 'danger');
$meta['delUserRefs']      = array('','_caution' => 'danger');
$meta['updateUser']       = array('string','_caution' => 'danger');
$meta['UpdateLogin']      = array('string','_caution' => 'danger');
$meta['UpdatePass']       = array('string','_caution' => 'danger');
$meta['UpdateEmail']      = array('string','_caution' => 'danger');
$meta['UpdateName']       = array('string','_caution' => 'danger');
$meta['UpdateTarget']     = array('string','_caution' => 'danger');
$meta['delUserGroup']     = array('','_caution' => 'danger');
$meta['getGroupID']       = array('','_caution' => 'danger');
